--------------------------------------------------------
--  ファイルを作成しました - 月曜日-2月-15-2016   
--------------------------------------------------------
--------------------------------------------------------

--  DDL for Table LINE

--------------------------------------------------------


  CREATE TABLE "LINGUISTICS"."LINE" 
   (	"NUMBEROFWORDS" NUMBER(10,0), 
	"PIECE" VARCHAR2(255 BYTE), 
	"AUTHOR" VARCHAR2(255 BYTE), 
	"LINENUMBER" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------

--  DDL for Index SYS_C008287

--------------------------------------------------------


  CREATE UNIQUE INDEX "LINGUISTICS"."SYS_C008287" ON "LINGUISTICS"."LINE" ("PIECE", "AUTHOR", "LINENUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------

--  Constraints for Table LINE

--------------------------------------------------------


  ALTER TABLE "LINGUISTICS"."LINE" ADD PRIMARY KEY ("PIECE", "AUTHOR", "LINENUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "LINGUISTICS"."LINE" MODIFY ("LINENUMBER" NOT NULL ENABLE);
  ALTER TABLE "LINGUISTICS"."LINE" MODIFY ("AUTHOR" NOT NULL ENABLE);
  ALTER TABLE "LINGUISTICS"."LINE" MODIFY ("PIECE" NOT NULL ENABLE);

--------------------------------------------------------
--  ファイルを作成しました - 月曜日-2月-15-2016   
--------------------------------------------------------
--------------------------------------------------------

--  DDL for Table LINE_WORDS

--------------------------------------------------------


  CREATE TABLE "LINGUISTICS"."LINE_WORDS" 
   (	"PIECE" VARCHAR2(255 BYTE), 
	"AUTHOR" VARCHAR2(255 BYTE), 
	"LINENUMBER" NUMBER(10,0), 
	"WORDIDS" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------

--  Ref Constraints for Table LINE_WORDS

--------------------------------------------------------


  ALTER TABLE "LINGUISTICS"."LINE_WORDS" ADD CONSTRAINT "FK_LINE_WORDS_PIECE" FOREIGN KEY ("PIECE", "AUTHOR", "LINENUMBER")
	  REFERENCES "LINGUISTICS"."LINE" ("PIECE", "AUTHOR", "LINENUMBER") ENABLE;

--------------------------------------------------------
--  ファイルを作成しました - 月曜日-2月-15-2016   
--------------------------------------------------------
--------------------------------------------------------

--  DDL for Table WORD

--------------------------------------------------------


  CREATE TABLE "LINGUISTICS"."WORD" 
   (	"WORDID" NUMBER(10,0), 
	"BASEFROM" VARCHAR2(255 BYTE), 
	"PARTOFSPEECH1" VARCHAR2(255 BYTE), 
	"PARTOFSPEECH2" VARCHAR2(255 BYTE), 
	"READING" VARCHAR2(255 BYTE), 
	"SURFACEFORM" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------

--  DDL for Index SYS_C008289

--------------------------------------------------------


  CREATE UNIQUE INDEX "LINGUISTICS"."SYS_C008289" ON "LINGUISTICS"."WORD" ("WORDID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------

--  Constraints for Table WORD

--------------------------------------------------------


  ALTER TABLE "LINGUISTICS"."WORD" ADD PRIMARY KEY ("WORDID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "LINGUISTICS"."WORD" MODIFY ("WORDID" NOT NULL ENABLE);

exit
